# Faye
development:
  server:  "http://138.68.17.221:9292/faye" 
  # server:  "http://localhost:9292/faye"
  adapter_javascript_url: "http://138.68.17.221:9292/faye/faye.js" 
  # adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  auth_token:  "97c42058e1466902d5adfac0f83e84c1794b9c3390e3b0824be9db8344eae82b"
  adapter: "Faye"
  async: true

# Pusher
# development:
#   adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js"
#   app_id: "YOUR_PUSHER_APP_ID"
#   api_key: "YOUR_PUSHER_API_KEY"
#   auth_token: "YOUR_PUSHER_SECRET"
#   adapter: "Pusher"
#   async: true

# Disabled
# development:
#   adapter: false

test:
  server:  "http://138.68.17.221:9292/faye" 
  # server:  "http://localhost:9292/faye"
  adapter_javascript_url: "http://138.68.17.221:9292/faye/faye.js" 
  # adapter_javascript_url: "http://localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "97c42058e1466902d5adfac0f83e84c1794b9c3390e3b0824be9db8344eae82b"
  async: false

production:
  server:  "http://138.68.17.221:9292/faye" 
  # server:  "http://localhost:9292/faye"
  adapter_javascript_url: "http://138.68.17.221:9292/faye/faye.js" 
  # adapter_javascript_url: "http:localhost:9292/faye/faye.js"
  adapter: "Faye"
  auth_token: "97c42058e1466902d5adfac0f83e84c1794b9c3390e3b0824be9db8344eae82b"
  async: true
